{{ template "vault.mode" . }}
{{- if ne .mode "external" }}
{{- if and (ne .mode "") (and (eq (.Values.global.enabled | toString) "true") (eq (.Values.server.authDelegator.enabled | toString) "true") (eq (.Values.server.letsencrypt.enabled | toString) "true")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-letsencrypt
  namespace: {{ .Release.Namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.server.letsencrypt.volumeSize }}
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gp2"
{{- end }}
{{- end }}
