{{ template "vault.mode" . }}
{{- if false }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "vault.fullname" . }}-letsencrypt-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-letsencrypt-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- template "vault.statefulSet.annotations" . }}
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    metadata:
      labels:
        helm.sh/chart: {{ template "vault.chart" . }}
        app.kubernetes.io/name: {{ template "vault.name" . }}-letsencrypt-cronjob
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: server
        {{- if  .Values.server.extraLabels -}}
          {{- toYaml .Values.server.extraLabels | nindent 8 -}}
        {{- end -}}
      {{ template "vault.annotations" . }}
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ template "vault.fullname" . }}
          volumes:
            - name: letsencrypt-script
              configMap:
                name: {{ template "vault.fullname" . }}-letsencrypt-create-certificate-script
            - name: letsencrypt-ovhapi
              secret:
                secretName: letsencrypt-ovhapi
                defaultMode: 256
          initContainers:
            - name: letsencrypt-cronjob-init
              image: certbot/dns-ovh:v1.8.0
              imagePullPolicy: {{ .Values.server.image.pullPolicy }}
              command:
                - /bin/sh
                - '-ec'
              args:
                - >
                  echo "USER";
                  echo $USER;
                  id;
                  echo $HOME;
                  echo "pwd";
                  pwd;
                  pip install --upgrade pip;
                  pip install kubernetes;
                  mkdir /opt/letsencrypt;
                  certbot certonly --dry-run -m admin@singlespot.com --agree-tos --dns-ovh --dns-ovh-credentials \
                    /root/config/ovh.ini -d vault-dev.singlespot.com --rsa-key-size 4096 --config-dir \
                    /opt/letsencrypt/config --work-dir /opt/letsencrypt/work --logs-dir /opt/letsencrypt/logs \
                    --non-interactive;
                  python /root/script/create_cert_secret.py
              env: []
              volumeMounts:
                - name: letsencrypt-script
                  mountPath: /root/script/
                - name: letsencrypt-ovhapi
                  readOnly: true
                  mountPath: /root/config/
          containers:
            - name: letsencrypt-cronjob
              image: certbot/dns-ovh:v1.8.0
              imagePullPolicy: {{ .Values.server.image.pullPolicy }}
              command:
                - /bin/sh
                - '-ec'
              args:
                - >
                  echo "USER";
                  echo $USER;
                  id
              env: []
              volumeMounts:
                - name: letsencrypt-script
                  mountPath: /root/config/
                - name: letsencrypt-ovhapi
                  readOnly: true
                  mountPath: /root/script/
{{ end }}
